# Generated by Django 5.0 on 2023-12-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_income', models.IntegerField()),
                ('customer_debt', models.IntegerField()),
                ('payment_remarks_12m', models.IntegerField()),
                ('payment_remarks', models.IntegerField()),
                ('customer_age', models.IntegerField()),
            ],
        ),
    ]
